import pyautogui as pyauto
import time

cpf = str(input("CPF: "))
parcela = str(input("Qual a parcela? [X de Y]: "))
descricao = str(input("Descrição do projeto: "))
valor = str(input("Qual o valor: "))

pyauto.moveTo(1300, 700, 0.5, pyauto.easeOutQuad)
pyauto.click()
pyauto.scroll(20)

time.sleep(0.5)
pyauto.moveTo(650, 700, 0.5, pyauto.easeOutQuad)
pyauto.click()
time.sleep(1)
pyauto.click()
pyauto.write(cpf, 0.25)
pyauto.moveTo(800, 700, 0.5, pyauto.easeOutQuad)
pyauto.click()
    
time.sleep(1)
pyauto.scroll(-10)
pyauto.moveTo(750, 690, 0.5, pyauto.easeOutQuad)
pyauto.click()

time.sleep(1)
pyauto.moveTo(670, 630, 0.5, pyauto.easeOutQuad)
pyauto.click()
pyauto.moveTo(670, 700, 0.5, pyauto.easeOutQuad)
pyauto.click()
time.sleep(2)
pyauto.scroll(-10)
pyauto.moveTo(790, 360, 0.5, pyauto.easeOutQuad)
pyauto.click()
pyauto.moveTo(790, 400, 0.5, pyauto.easeOutQuad)
pyauto.click()
time.sleep(2)
pyauto.scroll(-10)
pyauto.moveTo(820, 450, 0.5, pyauto.easeOutQuad)
pyauto.click()

time.sleep(2)
pyauto.scroll(-7)
pyauto.moveTo(840, 400, 0.5, pyauto.easeOutQuad)
pyauto.click()
pyauto.write("Nota referente à parcela: " + parcela + "\n" + descricao + "\n" + "Associação civil sem fins lucrativos, de caráter estudantil, isenta de retenção na fonte quando das contribuições PIS, CONFINS e CSSL. Conforme Lei 9.532/1997 quando desenvolve atividades fins estatutárias / não está sujeita a retenção previdenciária prevista in rfb 971/2009 por não se tratar de cessão de mão-de-obra / não estão sujeitas a desconto do imposto de renda na fonte sobre rendimentos pela prestação de serviços pela atividade fim conforme in rfb 23/1986")
pyauto.moveTo(575, 520, 0.5, pyauto.easeOutQuad)
pyauto.click()
pyauto.write("Projeto")
pyauto.moveTo(732, 520, 0.5, pyauto.easeOutQuad)
pyauto.click()
pyauto.write("1")
pyauto.moveTo(832, 520, 0.5, pyauto.easeOutQuad)
pyauto.click()
pyauto.write(valor)

pyauto.alert(text='Finalizado', button='OK')